### ISSUE TITLE
Getting the static salt

### ISSUE THREAD

**Issue by k1nnx** [derrod/warfra_re#1]
# How did you manage to obtain the static salt from the app?
### I've managed to look at the salt, but i have no way of converting it, do you need to whirlpool the value of the salt?
I cannot use hexlify since it has negative values.

# Images
![image](https://user-images.githubusercontent.com/119894400/222321839-a6b47710-35fb-4170-856a-451087a8e71a.png)
![image](https://user-images.githubusercontent.com/119894400/222321791-7307d7dd-f63a-400e-a5d1-e86826c2a20f.png)

Thanks!

**Comment by derrod** [comment]
I don't know what that salt is but to convert it from signed to unsugned this should work:
https://github.com/derrod/warfra_re/blob/51a5b6be48b6d9d1b1cd070d1e317e652c783d83/scripts/decrypt_resources.py#L11
